spring.application.name=insurance-policy-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/insurance}
spring.datasource.username=${DB_USERNAME:insurance_user}
spring.datasource.password=${DB_PASSWORD:insurance_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.sam.insurance=INFO

app.jwt.secret=${JWT_SECRET:VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdEZXZlbG9wbWVudFNlY3JldEtleTEyMzQ1Ng==}