apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: insurance
type: Opaque
stringData:
  POSTGRES_USER: replace_me
  POSTGRES_PASSWORD: replace_me
  POSTGRES_DB: insurance

---
apiVersion: v1
kind: Secret
metadata:
  name: insurance-api-secret
  namespace: insurance
type: Opaque
stringData:
  DB_PASSWORD: replace_me
  JWT_SECRET: replace_me
