CREATE TABLE policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    policy_number VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,

    premium NUMERIC(12, 2) NOT NULL,

    status VARCHAR(255) NOT NULL,

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    CONSTRAINT uk_policy_number
        UNIQUE (policy_number),

    CONSTRAINT chk_policy_status
        CHECK (
            status IN (
                'PENDING',
                'ACTIVE',
                'CANCELLED',
                'EXPIRED'
            )
        ),

    CONSTRAINT chk_policy_dates
        CHECK (end_date > start_date),

    CONSTRAINT chk_policy_premium
        CHECK (premium > 0)
);